include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - android/**
    - build/**
    - ios/**
    - linux/**
    - macos/**
    - web/**
    - windows/**
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    avoid_print: true
    directives_ordering: true
    prefer_final_fields: true
    prefer_final_locals: true
    use_super_parameters: true
