#include "game_internal.h"

#include <stdint.h>

int odg_content_registry_validate(void){
    uint32_t i,j;
    /* Every public item ID must be backed by its exact table slot. */
    for(i=1u;i<ODG_ITEM_TYPE_COUNT;++i){
        const odg_item_definition *d=odg_item_definition_internal(i);
        if(d==NULL||d->type_id!=i||d->max_stack==0u||!odg_item_attack_profile_valid_internal(i))return 0;
        /* Direct HUNT interactions are real weapon strikes. A hunting-capable item must
         * therefore opt into ATTACK and its validated damage profile instead of silently
         * inheriting the legacy one-HP-per-frame behavior. */
        if((d->capability_bits&ODG_ITEM_CAP_HUNT)!=0u&&(d->capability_bits&ODG_ITEM_CAP_ATTACK)==0u)return 0;
    }
    for(i=0u;i<odg_food_definition_count();++i){odg_food_definition f;uint64_t req=0u;const odg_item_definition *item;if(odg_food_definition_get(i,&f,sizeof(f),&req)!=ODG_STATUS_OK)return 0;item=odg_item_definition_internal(f.item_type);if(item==NULL||(item->capability_bits&ODG_ITEM_CAP_CONSUME)==0u)return 0;}
    for(i=0u;i<odg_fluid_definition_count();++i){odg_fluid_definition f;uint64_t req=0u;if(odg_fluid_definition_get(i,&f,sizeof(f),&req)!=ODG_STATUS_OK)return 0;if(f.fluid_id==ODG_FLUID_NONE||f.hydration_restore_per_unit==0u||f.flags==0u)return 0;for(j=i+1u;j<odg_fluid_definition_count();++j){odg_fluid_definition b;if(odg_fluid_definition_get(j,&b,sizeof(b),&req)!=ODG_STATUS_OK)return 0;if(b.fluid_id==f.fluid_id)return 0;}}
    for(i=0u;i<odg_fluid_container_definition_count();++i){odg_fluid_container_definition c;uint64_t req=0u;const odg_item_definition *item;if(odg_fluid_container_definition_get(i,&c,sizeof(c),&req)!=ODG_STATUS_OK)return 0;item=odg_item_definition_internal(c.item_type);if(item==NULL||c.capacity_units==0u||c.accepted_fluid_flags==0u||(item->capability_bits&ODG_ITEM_CAP_DRINK)==0u)return 0;}
    for(i=0u;i<odg_flora_species_count();++i){odg_flora_species_definition f;uint64_t req=0u;const odg_item_definition *seed,*fruit,*harvest,*tool;if(odg_flora_species_get(i,&f,sizeof(f),&req)!=ODG_STATUS_OK)return 0;seed=odg_item_definition_internal(f.seed_item_type);fruit=odg_item_definition_internal(f.fruit_item_type);harvest=odg_item_definition_internal(f.harvest_item_type);tool=f.harvest_tool_item_type==ODG_ITEM_NONE?NULL:odg_item_definition_internal(f.harvest_tool_item_type);if(f.species_id==0u||seed==NULL||fruit==NULL||harvest==NULL)return 0;if((seed->capability_bits&ODG_ITEM_CAP_PLANT)==0u||(fruit->capability_bits&ODG_ITEM_CAP_CONSUME)==0u||odg_food_definition_internal(f.fruit_item_type)==NULL)return 0;if(f.harvest_tool_item_type!=ODG_ITEM_NONE&&(tool==NULL||(tool->capability_bits&(ODG_ITEM_CAP_HARVEST|ODG_ITEM_CAP_MINE))==0u))return 0;if(f.seedling_ticks==0u||f.fruit_capacity_max<f.fruit_capacity_min||f.min_growth_moisture_permille>1000u||f.preferred_growth_moisture_permille>1000u||f.seed_germination_permille>1000u||f.fruit_seed_recovery_permille>1000u||f.fallen_fruit_seed_permille>1000u)return 0;for(j=i+1u;j<odg_flora_species_count();++j){odg_flora_species_definition b;if(odg_flora_species_get(j,&b,sizeof(b),&req)!=ODG_STATUS_OK)return 0;if(b.species_id==f.species_id)return 0;}}
    for(i=0u;i<odg_fauna_species_count();++i){odg_fauna_species_definition f;uint64_t req=0u;if(odg_fauna_species_get(i,&f,sizeof(f),&req)!=ODG_STATUS_OK)return 0;if(f.species_id==0u||f.max_health==0u||f.wild_population_hard_cap<f.wild_population_target||f.offspring_max<f.offspring_min||f.hydration_decay_ticks==0u||f.drink_below_permille>1000u||f.breeding_min_hydration_permille>1000u)return 0;if(f.reproduction_mode!=ODG_FAUNA_REPRO_EGG&&f.reproduction_mode!=ODG_FAUNA_REPRO_LIVE&&f.reproduction_mode!=ODG_FAUNA_REPRO_SPAWN&&f.reproduction_mode!=ODG_FAUNA_REPRO_NONE)return 0;if(f.reproduction_mode==ODG_FAUNA_REPRO_NONE&&(f.offspring_min!=0u||f.offspring_max!=0u||f.gestation_or_incubation_ticks!=0u))return 0;if(f.reproduction_mode!=ODG_FAUNA_REPRO_NONE&&(f.offspring_min==0u||f.gestation_or_incubation_ticks==0u))return 0;if((f.behavior_flags&ODG_FAUNA_BEHAVIOR_CAN_FLY)==0u&&f.flight_speed_milli_per_s!=0u)return 0;if((f.behavior_flags&ODG_FAUNA_BEHAVIOR_AQUATIC)!=0u&&(f.behavior_flags&ODG_FAUNA_BEHAVIOR_CAN_FLY)!=0u)return 0;if((f.behavior_flags&ODG_FAUNA_BEHAVIOR_OUTSIDE_TERRITORY_HUNTER)!=0u&&(f.behavior_flags&ODG_FAUNA_BEHAVIOR_HOSTILE_ACTORS)==0u)return 0;for(j=i+1u;j<odg_fauna_species_count();++j){odg_fauna_species_definition b;if(odg_fauna_species_get(j,&b,sizeof(b),&req)!=ODG_STATUS_OK)return 0;if(b.species_id==f.species_id)return 0;}}
    for(i=0u;i<odg_fauna_diet_count();++i){odg_fauna_diet_definition d;uint64_t req=0u;if(odg_fauna_diet_get(i,&d,sizeof(d),&req)!=ODG_STATUS_OK)return 0;if(odg_fauna_species_internal(d.fauna_species_id)==NULL||odg_item_definition_internal(d.item_type)==NULL||(d.satiety_restore==0u&&d.hydration_restore==0u))return 0;}
    for(i=0u;i<odg_fauna_habitat_count();++i){odg_fauna_habitat_definition h;uint64_t req=0u;const odg_fauna_species_definition *species;if(odg_fauna_habitat_get(i,&h,sizeof(h),&req)!=ODG_STATUS_OK)return 0;species=odg_fauna_species_internal(h.fauna_species_id);if(species==NULL||h.biome_mask==0u||h.min_altitude_milli>h.max_altitude_milli||h.min_moisture_permille>h.max_moisture_permille||h.max_moisture_permille>1000u||h.migration_interval_ticks==0u||h.ambient_water_interval_ticks==0u)return 0;if((species->behavior_flags&ODG_FAUNA_BEHAVIOR_FORAGE)!=0u){if(h.ambient_forage_interval_ticks==0u||h.ambient_forage_restore==0u)return 0;}else if(h.ambient_forage_interval_ticks!=0u||h.ambient_forage_restore!=0u)return 0;for(j=i+1u;j<odg_fauna_habitat_count();++j){odg_fauna_habitat_definition b;if(odg_fauna_habitat_get(j,&b,sizeof(b),&req)!=ODG_STATUS_OK)return 0;if(b.fauna_species_id==h.fauna_species_id)return 0;}}
    for(i=0u;i<odg_fauna_nesting_count();++i){odg_fauna_nesting_definition n;uint64_t req=0u;uint32_t allowed=ODG_NEST_SUBSTRATE_TREE|ODG_NEST_SUBSTRATE_GROUND|ODG_NEST_SUBSTRATE_CLIFF|ODG_NEST_SUBSTRATE_STRUCTURE;if(odg_fauna_nesting_get(i,&n,sizeof(n),&req)!=ODG_STATUS_OK)return 0;if(odg_fauna_species_internal(n.fauna_species_id)==NULL||n.substrate_mask==0u||(n.substrate_mask&~allowed)!=0u||n.search_range_milli==0u||n.nest_spacing_milli==0u||n.max_ground_slope_permille>1000u)return 0;if((n.substrate_mask&ODG_NEST_SUBSTRATE_TREE)!=0u&&(n.min_host_flora_stage<ODG_FLORA_STAGE_SEEDLING||n.min_host_flora_stage>ODG_FLORA_STAGE_OLD))return 0;for(j=i+1u;j<odg_fauna_nesting_count();++j){odg_fauna_nesting_definition b;if(odg_fauna_nesting_get(j,&b,sizeof(b),&req)!=ODG_STATUS_OK)return 0;if(b.fauna_species_id==n.fauna_species_id)return 0;}}
    for(i=0u;i<odg_fauna_species_count();++i){odg_fauna_species_definition f;uint64_t req=0u;if(odg_fauna_species_get(i,&f,sizeof(f),&req)!=ODG_STATUS_OK)return 0;if(odg_fauna_habitat_internal(f.species_id)==NULL)return 0;if(f.reproduction_mode==ODG_FAUNA_REPRO_EGG){if((f.behavior_flags&ODG_FAUNA_BEHAVIOR_NESTING)==0u||odg_fauna_nesting_internal(f.species_id)==NULL)return 0;}else if(odg_fauna_nesting_internal(f.species_id)!=NULL)return 0;}
    for(i=0u;i<odg_loot_table_count();++i){odg_loot_table_definition t;uint64_t req=0u;if(odg_loot_table_get(i,&t,sizeof(t),&req)!=ODG_STATUS_OK||t.entry_count>ODG_LOOT_MAX_ENTRIES)return 0;for(j=0u;j<t.entry_count;++j)if(odg_item_definition_internal(t.entries[j].item_type)==NULL||t.entries[j].quantity_max<t.entries[j].quantity_min||t.entries[j].chance_permille>1000u)return 0;}
    if(!odg_artifact_profiles_validate_internal()||!odg_construction_profiles_validate_internal()||
       !odg_inventory_expanders_validate_internal()||!odg_resource_profiles_validate_internal()||
       !odg_recipe_profiles_validate_internal()||!odg_fauna_profiles_validate_internal()||
       !odg_turret_profiles_validate_internal())return 0;
    return 1;
}
